[workspace]

members = [
    "libs/megadrive-sys",
    "libs/megadrive-input",
    "libs/megadrive-graphics",
    "tools/cargo-megadrive",
    "examples/megapong",
]

[profile.release]
lto = true
panic = "abort"

[profile.dev]
panic = "abort"
