---
version: "3.2"

services:
  m68k-app-builder:
    image: quay.io/reinvantveer/rust-m68k-megadrive:1.53.0-dev
    environment:
      - MEGADRIVE_HOME=/rust-mega-drive/share
      - RUSTUP_TOOLCHAIN=m68k
      - LLVM_CONFIG=/llvm-m68k/bin/llvm-config
    volumes:
    - ./target:/target
#    command: ["ls", "/rust-mega-drive"]
