on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build llvm-m68k
        run: |
          sudo apt-get install -y ninja-build
          git clone -b llvm-12 --single-branch https://github.com/ricky26/llvm-project llvm-m68k
          cd llvm-m68k
          mkdir build
          cd build
          cmake \
            -S ../llvm \
            -G Ninja \
            "-DLLVM_USE_LINKER=gold" \
            "-DCMAKE_BUILD_TYPE=RelWithDebInfo" \
            "-DLLVM_ENABLE_ASSERTIONS=ON" \
            "-DLLVM_PARALLEL_LINK_JOBS=1" \
            "-DLLVM_TARGETS_TO_BUILD=X86" \
            "-DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=M68k" \
            "-DLLVM_ENABLE_PROJECTS=clang;lld" \
            ..
          ninja -j4
